import requests
from bs4 import BeautifulSoup as bs
import pandas as pd
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36'
}

url = "" # I prefer not to show website url
num_players = 18180  # set the number of players to scrape and this website has 18180 players 
players = [{} for _ in range(num_players)]  # create an empty list of dictionaries

for offset in range(0, num_players, 60): # Creating an loop for page requests 
    page_url = url + str(offset) 
    response = requests.get(page_url, headers=headers)
    soup = bs(response.content, 'html.parser') 
    table = soup.find_all("tbody",{"class":"list"})
    for i, row in enumerate(table[0].find_all('tr')): # loop for each elements in the table
        player = {}
        c1 = table[0].find_all('td',{"class":"col-avatar"})[i]
        player['player_id']=c1.img["id"]
        player['img_link']=c1.img["data-src"]
        c3=table[0].find_all('td',{"class":"col col-ae"})[i]
        player['age']=c3.text
        c4=table[0].find_all('td',{"class":"col col-oa col-sort"})[i]
        player['overall']=c4.text
        c5=table[0].find_all('td',{"class":"col col-pt"})[i]
        player['potential']=c5.text
        c7=table[0].find_all('td',{"class":"col col-hi"})[i]
        player['height']=c7.text
        c8=table[0].find_all('td',{"class":"col col-wi"})[i]
        player['weight']=c8.text
        c9=table[0].find_all('td',{"class":"col col-pf"})[i]
        player['preferred_foot']=c9.text
        c10=table[0].find_all('td',{"class":"col col-bo"})[i]
        player['best_overall']=c10.text
        c11=table[0].find_all('td',{"class":"col col-vl"})[i]
        player['value']=c11.text
        c12=table[0].find_all('td',{"class":"col col-wg"})[i]
        player['wage']=c12.text
        c13=table[0].find_all('td',{"class":"col col-rc"})[i]
        player['release_clause']=c13.text
        c14=table[0].find_all('td',{"class":"col col-ta"})[i]
        player['total_attacking']=c14.text
        c15=table[0].find_all('td',{"class":"col col-cr"})[i]
        player['crossing']=c15.text
        c16=table[0].find_all('td',{"class":"col col-fi"})[i]
        player['finishing']=c16.text
        c17=table[0].find_all('td',{"class":"col col-he"})[i]
        player['heading']=c15.text
        c18=table[0].find_all('td',{"class":"col col-sh"})[i]
        player['short_passing']=c18.text
        c19=table[0].find_all('td',{"class":"col col-vo"})[i]
        player['volleys']=c19.text
        c20=table[0].find_all('td',{"class":"col col-ts"})[i]
        player['total_skill']=c20.text
        c21=table[0].find_all('td',{"class":"col col-dr"})[i]
        player['dribbling']=c21.text
        c22=table[0].find_all('td',{"class":"col col-cu"})[i]
        player['curve']=c22.text
        c23=table[0].find_all('td',{"class":"col col-fr"})[i]
        player['fk_accuracy']=c23.text
        c24=table[0].find_all('td',{"class":"col col-lo"})[i]
        player['long_pass']=c24.text
        c25=table[0].find_all('td',{"class":"col col-bl"})[i]
        player['ball_control']=c25.text
        c26=table[0].find_all('td',{"class":"col col-to"})[i]
        player['total_movement']=c26.text
        c27=table[0].find_all('td',{"class":"col col-ac"})[i]
        player['acceleration']=c27.text
        c28=table[0].find_all('td',{"class":"col col-sp"})[i]
        player['sprint_speed']=c28.text
        c29=table[0].find_all('td',{"class":"col col-ag"})[i]
        player['agility']=c29.text
        c30=table[0].find_all('td',{"class":"col col-re"})[i]
        player['reation']=c30.text
        c31=table[0].find_all('td',{"class":"col col-ba"})[i]
        player['balance']=c31.text
        c32=table[0].find_all('td',{"class":"col col-tp"})[i]
        player['total_power']=c32.text
        c33=table[0].find_all('td',{"class":"col col-so"})[i]
        player['shot_power']=c33.text
        c34=table[0].find_all('td',{"class":"col col-ju"})[i]
        player['jumping']=c34.text
        c35=table[0].find_all('td',{"class":"col col-st"})[i]
        player['stamina']=c35.text
        c36=table[0].find_all('td',{"class":"col col-sr"})[i]
        player['strength']=c36.text
        c37=table[0].find_all('td',{"class":"col col-ln"})[i]
        player['long_shot']=c37.text
        c38=table[0].find_all('td',{"class":"col col-te"})[i]
        player['total_mentality']=c38.text
        c39=table[0].find_all('td',{"class":"col col-ar"})[i]
        player['aggression']=c39.text
        c40=table[0].find_all('td',{"class":"col col-in"})[i]
        player['interceptions']=c40.text
        c41=table[0].find_all('td',{"class":"col col-po"})[i]
        player['positioning']=c41.text
        c42=table[0].find_all('td',{"class":"col col-vi"})[i]
        player['vision']=c42.text
        c43=table[0].find_all('td',{"class":"col col-pe"})[i]
        player['penalties']=c43.text
        c44=table[0].find_all('td',{"class":"col col-cm"})[i]
        player['composure']=c44.text
        c46=table[0].find_all('td',{"class":"col col-td"})[i]
        player['total_defending']=c46.text
        c47=table[0].find_all('td',{"class":"col col-ma"})[i]
        player['marking']=c47.text
        c48=table[0].find_all('td',{"class":"col col-sa"})[i]
        player['standing_tackle']=c48.text
        c49=table[0].find_all('td',{"class":"col col-sl"})[i]
        player['sliding_tackle']=c49.text
        c50=table[0].find_all('td',{"class":"col col-tg"})[i]
        player['total_goalkeeping']=c50.text
        c51=table[0].find_all('td',{"class":"col col-gd"})[i]
        player['gk_diving']=c51.text
        c52=table[0].find_all('td',{"class":"col col-gh"})[i]
        player['gk_handling']=c52.text
        c53=table[0].find_all('td',{"class":"col col-gc"})[i]
        player['gk_kicking']=c53.text
        c54=table[0].find_all('td',{"class":"col col-gp"})[i]
        player['gk_positioning']=c54.text
        c55=table[0].find_all('td',{"class":"col col-gr"})[i]
        player['gk_reflexes']=c55.text
        c56=table[0].find_all('td',{"class":"col col-tt"})[i]
        player['total_stats']=c56.text
        c57=table[0].find_all('td',{"class":"col col-bs"})[i]
        player['base_stats']=c57.text
        c58=table[0].find_all('td',{"class":"col col-wk"})[i]
        player['weak_foot']=c58.text
        c59=table[0].find_all('td',{"class":"col col-sk"})[i]
        player['skill_move']=c59.text
        c60=table[0].find_all('td',{"class":"col col-ir"})[i]
        player['international_reputation']=c60.text
        c61=table[0].find_all('td',{"class":"col col-bt"})[i]
        player['body']=c61.text
        c62=table[0].find_all('td',{"class":"col col-pac"})[i]
        player['pac']=c62.text
        c63=table[0].find_all('td',{"class":"col col-sho"})[i]
        player['sho']=c63.text
        c64=table[0].find_all('td',{"class":"col col-pas"})[i]
        player['pas']=c64.text
        c65=table[0].find_all('td',{"class":"col col-dri"})[i]
        player['dri']=c65.text
        c66=table[0].find_all('td',{"class":"col col-def"})[i]
        player['defn']=c66.text
        c67=table[0].find_all('td',{"class":"col col-phy"})[i]
        player['phy']=c67.text
        players[offset+i] = player

data=pd.DataFrame(players)
data.to_excel('data.xlsx')